### ISSUE TITLE
Error when creating mempool 

### ISSUE THREAD

**Issue by maxwellxxx** [marty90/DPDK-Dump#2]
Hi,
I got a error like this:

PMD: rte_cxgbe_pmd:  0000:81:00.4 Chelsio rev 0 1000/10GBASE-SFP 
PMD: rte_cxgbe_pmd:  0000:81:00.4 Chelsio rev 0 1000/10GBASE-SFP 
EAL: Error - exiting with code: 1
  Cause: Cannot create cluster_mem_pool. Errno: 12 [ENOMEM: 12, ENOSPC: 28,E_RTE_NO_CONFIG: 1002, E_RTE_SECONDARY: 1001, EINVAL: 22, EEXIST: 17]

When I ran the l2fwd, there was on erros.

**Comment by marty90** [comment]
Hi maxwellxxx.
You see that error message because your system doesn't have enough free hugepages.
There are 2 solutions possible:
1. Reserve more hugepages in your system (if there is enough RAM on the machine). See point 4.1 in DPDK-Dump readme.
2. Decrease the size of DPDK-Dump internal buffer with "-B" option. Default size is 1 Milion packets which means about 2GB of memory.

**Comment by maxwellxxx** [comment]
Hi~~
 Thanks for your detailed answer, I have solved the problem. But I get another error, like this:

"PMD: rte_cxgbe_pmd: fw: 1.11.27.0, TP: 0.1.4.7
PMD: rte_cxgbe_pmd: Coming up as MASTER: Initializing adapter
PMD: rte_cxgbe_pmd: adap_init0_config: Going for embedded config in firmware..
PMD: rte_cxgbe_pmd: Successfully configured using Firmware Configuration File "Firmware Default", version 0, computed checksum 0
PMD: rte_cxgbe_pmd:  0000:81:00.4 Chelsio rev 0 1000/10GBASE-SFP 
PMD: rte_cxgbe_pmd:  0000:81:00.4 Chelsio rev 0 1000/10GBASE-SFP 
Name:rte_cxgbe_pmd
    Driver name: rte_cxgbe_pmd
    Max rx queues: 2
    Max tx queues: 2
    PCI Adress: 0000:129:00:4
EAL: Error - exiting with code: 1
  Cause: Error configuring receiving queue stats"

With the hugepages is 10240 and buffer size is 1048576. The Ram on my system is 128GB,

The doc of DPDK has no record of the error of rte_eth_dev_set_rx_queue_stats_mapping()...

**Comment by marty90** [comment]
Strange: which version of DPDK are you using?
which NICs are you using?

**Comment by maxwellxxx** [comment]
Hi,
The version of DPDK is newest. And my NIC is "Chelsio T520-CR" which is supported by DPDK officially.

**Comment by marty90** [comment]
Ok, this might be the problem.
Install DPDK 1.8.0 ( http://dpdk.org/browse/dpdk/snapshot/dpdk-1.8.0.tar.gz )
In DPDK-Dump's readme you find the commands to install it.

**Comment by maxwellxxx** [comment]
OK. Thank you. I'll have a try. ^_^

**Comment by promisechen** [comment]
hi,
 buffer size is 1048576! !?
I think it's too big for the value. and there is no need to set such a big.

**Comment by marty90** [comment]
A hard disk (no solid state) has a long time of seek and rotation. Thus, the writing thread can freeze up to 0.5 seconds. The buffer should be able to store 10Gbps traffic for such time.

**Comment by HaochuanXJTU** [comment]
I hava solved the problem by it.

**Comment by dutch3883** [comment]
I also got the same problem as maxwellxxx.
$sudo ./build/dpdk-dump -c 0x03 -n 2 -w 0000:05:00.1 -- -w dpdkdumpout.pcap -c 10000000 -B 16777216

I have checked the version of dpdk that it is 1.8.0.
Could someone help me, how to solve this problem?

EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 4 on socket 0
EAL: Detected lcore 5 as core 5 on socket 0
EAL: Detected lcore 6 as core 6 on socket 0
EAL: Detected lcore 7 as core 7 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: Setting up memory...
^[[BEAL: Ask a virtual area of 0x2a800000 bytes
EAL: Virtual area found at 0x7f349e600000 (size = 0x2a800000)
EAL: Ask a virtual area of 0x2ca00000 bytes
EAL: Virtual area found at 0x7f3471a00000 (size = 0x2ca00000)
EAL: Ask a virtual area of 0xc800000 bytes
EAL: Virtual area found at 0x7f3465000000 (size = 0xc800000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f3464a00000 (size = 0x400000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f3464400000 (size = 0x400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f3464000000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f3463c00000 (size = 0x200000)
EAL: Ask a virtual area of 0x4f4800000 bytes
EAL: Virtual area found at 0x7f2f6f200000 (size = 0x4f4800000)
EAL: Ask a virtual area of 0x91dc00000 bytes
EAL: Virtual area found at 0x7f2651400000 (size = 0x91dc00000)
EAL: Ask a virtual area of 0x71800000 bytes
EAL: Virtual area found at 0x7f25dfa00000 (size = 0x71800000)
EAL: Ask a virtual area of 0x1200000 bytes
EAL: Virtual area found at 0x7f25de600000 (size = 0x1200000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f25de000000 (size = 0x400000)
EAL: Ask a virtual area of 0xb800000 bytes
EAL: Virtual area found at 0x7f25d2600000 (size = 0xb800000)
EAL: Ask a virtual area of 0x6e00000 bytes
EAL: Virtual area found at 0x7f25cb600000 (size = 0x6e00000)
EAL: Ask a virtual area of 0x1000000 bytes
EAL: Virtual area found at 0x7f25ca400000 (size = 0x1000000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f25c9600000 (size = 0xc00000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f25c8c00000 (size = 0x800000)
EAL: Ask a virtual area of 0x1a00000 bytes
EAL: Virtual area found at 0x7f25c7000000 (size = 0x1a00000)
EAL: Ask a virtual area of 0x600000 bytes
EAL: Virtual area found at 0x7f25c6800000 (size = 0x600000)
EAL: Ask a virtual area of 0x1000000 bytes
EAL: Virtual area found at 0x7f25c5600000 (size = 0x1000000)
EAL: Ask a virtual area of 0xe00000 bytes
EAL: Virtual area found at 0x7f25c4600000 (size = 0xe00000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f25c3800000 (size = 0xc00000)
EAL: Ask a virtual area of 0x1200000 bytes
EAL: Virtual area found at 0x7f25c2400000 (size = 0x1200000)
EAL: Ask a virtual area of 0x4e00000 bytes
EAL: Virtual area found at 0x7f25bd400000 (size = 0x4e00000)
EAL: Ask a virtual area of 0x4800000 bytes
EAL: Virtual area found at 0x7f25b8a00000 (size = 0x4800000)
EAL: Ask a virtual area of 0x17400000 bytes
EAL: Virtual area found at 0x7f25a1400000 (size = 0x17400000)
EAL: Ask a virtual area of 0x5d800000 bytes
EAL: Virtual area found at 0x7f2543a00000 (size = 0x5d800000)
EAL: Ask a virtual area of 0xa00000 bytes
EAL: Virtual area found at 0x7f2542e00000 (size = 0xa00000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f2542800000 (size = 0x400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f2542400000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f2542000000 (size = 0x200000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f2541600000 (size = 0x800000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f2541200000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f2540e00000 (size = 0x200000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f2540800000 (size = 0x400000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f2540200000 (size = 0x400000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f253f400000 (size = 0xc00000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f253f000000 (size = 0x200000)
EAL: Ask a virtual area of 0x600000 bytes
EAL: Virtual area found at 0x7f253e800000 (size = 0x600000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f253e400000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f253e000000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f253dc00000 (size = 0x200000)
EAL: Requesting 31792 pages of size 2MB from socket 0
EAL: TSC frequency is ~1999999 KHz
EAL: Master core 0 is ready (tid=d2faa840)
PMD: ENICPMD trace: rte_enic_pmd_init
EAL: Core 1 is ready (tid=d0e82700)
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:05:00.1 not managed by VFIO driver, skipping
EAL:   PCI memory mapped at 0x7f34c8e00000
EAL:  ould PCI memory mapped at 0x7f34c8e20000
PMD: eth_igb_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x1521
Name:rte_igb_pmd
	Driver name: rte_igb_pmd
	Max rx queues: 8
	Max tx queues: 8
	PCI Adress: 0000:05:00:1
PMD: eth_igb_rx_queue_setup(): sw_ring=0x7f25ca0f1d80 hw_ring=0x7f25ca128580 dma_addr=0xf9ab28580
EAL: Error - exiting with code: 1
  Cause: Error configuring receiving queue stats

**Comment by yinxu1000** [comment]
**Hi,
I met an error as follow:**

PMD: eth_em_dev_init(): port_id 1 vendorID=0x8086 deviceID=0x100f
EAL: Error - exiting with code: 1
Cause: Cannot create cluster_mem_pool. Errno: 12 [ENOMEM: 12, ENOSPC: 28, E_RTE_NO_TAILQ: 1003, E_RTE_NO_CONFIG: 1002, E_RTE_SECONDARY: 1001, EINVAL: 22, EEXIST: 17]

**I found the solution of issue #2 and added -B. Now, A new error was appeared as follow:**

EAL: TSC frequency is ~2893583 KHz
EAL: Master core 0 is ready (tid=13d42800)
PMD: ENICPMD trace: rte_enic_pmd_init
EAL: Core 1 is ready (tid=8d9f2700)
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL: probe driver: 8086:100f rte_em_pmd
EAL: 0000:02:01.0 not managed by UIO driver, skipping
EAL: PCI device 0000:02:06.0 on NUMA socket -1
EAL: probe driver: 8086:100f rte_em_pmd
EAL: PCI memory mapped at 0x7f9212800000
EAL: PCI memory mapped at 0x7f9212820000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x100f
EAL: PCI device 0000:02:07.0 on NUMA socket -1
EAL: probe driver: 8086:100f rte_em_pmd
EAL: PCI memory mapped at 0x7f9212830000
EAL: PCI memory mapped at 0x7f9212850000
PMD: eth_em_dev_init(): port_id 1 vendorID=0x8086 deviceID=0x100f
Name:rte_em_pmd
Driver name: rte_em_pmd
Max rx queues: 1
Max tx queues: 1
PCI Adress: 0000:02:06:0
PMD: eth_em_rx_queue_setup(): sw_ring=0x7f9191aec000 hw_ring=0x7f91e2d93940 dma_addr=0x5b393940
EAL: Error - exiting with code: 1
Cause: Error configuring receiving queue stats

**I use dpdk-1.8.0, ubuntu 12.04 in VMware and Intel Corporation 82545EM (). Can you help me?**

**Comment by marty90** [comment]
Unfortunately it is a bug of DPDK.
For some NICs, _rte_eth_dev_set_rx_queue_stats_mapping()_ fails.
Try commenting line 324 of _src/main_dump.c_.
It should work, let me know.

**Comment by yinxu1000** [comment]
It works. Thank you for your help
