### ISSUE TITLE
Can not compile in dpdk.2.0

### ISSUE THREAD

**Issue by promisechen** [marty90/DPDK-Dump#3]
hi,
1. ETH_RSS_IPV4_TCP  not define 
            ETH_RSS_IPV4_TCP  ----->   ETH_RSS_NONFRAG_IPV4_TCP
2.E_RTE_NO_TAILQ not define

**Comment by marty90** [comment]
Please use DPDK 1.8 (available [here](http://dpdk.org/browse/dpdk/snapshot/dpdk-1.8.0.tar.gz)).
Support for DPDK 2.0 is anyway in the roadmap for the future.

**Comment by promisechen** [comment]
OK. Thank you. I'll have a try.
