### ISSUE TITLE
Cannot create cluster_mem_pool

### ISSUE THREAD

**Issue by HaochuanXJTU** [marty90/DPDK-Dump#4]
Hi, I have encountered a problem like that
root@haochuan-Lenovo-Product:/home/haochuan/DPDK-Dump# ./build/dpdk-dump -c 0x03 -n 4 -- -w capture.pcap -G 60 -w 30
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 2 lcore(s)
EAL:   cannot open VFIO container, error 2 (No such file or directory)
EAL: VFIO support could not be initialized
EAL: Setting up memory...
EAL: Ask a virtual area of 0x7800000 bytes
EAL: Virtual area found at 0x7f6d80400000 (size = 0x7800000)
EAL: Ask a virtual area of 0x51c00000 bytes
EAL: Virtual area found at 0x7f6d2e600000 (size = 0x51c00000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f6d2e000000 (size = 0x400000)
EAL: Ask a virtual area of 0x26800000 bytes
EAL: Virtual area found at 0x7f6d07600000 (size = 0x26800000)
EAL: Requesting 1024 pages of size 2MB from socket 0
EAL: TSC frequency is ~2925982 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master core 0 is ready (tid=8918e840)
PMD: ENICPMD trace: rte_enic_pmd_init
EAL: Core 1 is ready (tid=69f2700)
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f6d87c00000
EAL:   PCI memory mapped at 0x7f6d87c20000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:03:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f6d87c40000
EAL:   PCI memory mapped at 0x7f6d87c60000
PMD: eth_em_dev_init(): port_id 1 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f6d87c80000
EAL:   PCI memory mapped at 0x7f6d87ca0000
PMD: eth_em_dev_init(): port_id 2 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f6d87cc0000
EAL:   PCI memory mapped at 0x7f6d87ce0000
PMD: eth_em_dev_init(): port_id 3 vendorID=0x8086 deviceID=0x10bc
EAL: Error - exiting with code: 1
  Cause: Cannot create cluster_mem_pool. Errno: 12 [ENOMEM: 12, ENOSPC: 28, E_RTE_NO_TAILQ: 1003, E_RTE_NO_CONFIG: 1002, E_RTE_SECONDARY: 1001, EINVAL: 22, EEXIST: 17]

**Comment by marty90** [comment]
Hi, I think is the same problem of maxwelxxx.
Please see that discussion:
https://github.com/marty90/DPDK-Dump/issues/2

**Comment by marty90** [comment]
Try using a buffer of 65536 packets.

**Comment by HaochuanXJTU** [comment]
Thanks for you help,I have solved the problem,but there is another error:
root@haochuan-Lenovo-Product:/home/haochuan/DPDK-Dump# ./build/dpdk-dump -c 0x03 -n 4 -- -w capture.pcap
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 2 lcore(s)
EAL:   cannot open VFIO container, error 2 (No such file or directory)
EAL: VFIO support could not be initialized
EAL: Setting up memory...
EAL: Ask a virtual area of 0x5c00000 bytes
EAL: Virtual area found at 0x7f8acb600000 (size = 0x5c00000)
EAL: Ask a virtual area of 0x54000000 bytes
EAL: Virtual area found at 0x7f8a77400000 (size = 0x54000000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f8a77000000 (size = 0x200000)
EAL: Ask a virtual area of 0x26000000 bytes
EAL: Virtual area found at 0x7f8a50e00000 (size = 0x26000000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f8a50a00000 (size = 0x200000)
EAL: Requesting 1024 pages of size 2MB from socket 0
EAL: TSC frequency is ~2925982 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master core 0 is ready (tid=d2803840)
PMD: ENICPMD trace: rte_enic_pmd_init
EAL: Core 1 is ready (tid=4fdf2700)
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f8ad1200000
EAL:   PCI memory mapped at 0x7f8ad1220000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:03:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f8ad1240000
EAL:   PCI memory mapped at 0x7f8ad1260000
PMD: eth_em_dev_init(): port_id 1 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f8ad1280000
EAL:   PCI memory mapped at 0x7f8ad12a0000
PMD: eth_em_dev_init(): port_id 2 vendorID=0x8086 deviceID=0x10bc
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10bc rte_em_pmd
EAL:   PCI memory mapped at 0x7f8ad12c0000
EAL:   PCI memory mapped at 0x7f8ad12e0000
PMD: eth_em_dev_init(): port_id 3 vendorID=0x8086 deviceID=0x10bc
Name:rte_em_pmd
    Driver name: rte_em_pmd
    Max rx queues: 1
    Max tx queues: 1
    PCI Adress: 0000:03:00:0
PMD: eth_em_rx_queue_setup(): sw_ring=0x7f8acc0e0480 hw_ring=0x7f8a77128680 dma_addr=0x103128680
EAL: Error - exiting with code: 1
  Cause: Error configuring receiving queue stats
