### ISSUE TITLE
How to capture packets without missing in high speed network

### ISSUE THREAD

**Issue by yinxu1000** [marty90/DPDK-Dump#7]
Hi, 

Packets might be dropped when the speed is fast.

PORT:  0 Rx: 54013914 Drp: 7532022 Tot: 61545936 Perc: 12.238%
-------------------------------------------------
TOT:     Rx: 54013914 Drp: 7532022 Tot: 61545936 Perc: 12.238%

 I tried to use -c 0xf to allocate more cores, it returned error and said "exactly two cores". 

How can I set the parameters to capture packets without dropping packets?

Thank you very much.

Xu

**Comment by marty90** [comment]
Very often, when you loose packets, the bottleneck is the disk where you want to save them. Having more cores is useless.

**Comment by yinxu1000** [comment]
Thank you for answering. Are there any suggestions when dealing with packet lose situation?

**Comment by marty90** [comment]
To have a fast disk, you can configure a bunch of them in RAID 0 configuration to have one fast logical disk.
SSD (solid state disks) are reccomended.

**Comment by yinxu1000** [comment]
👍 I will try fast disk. Thanks again.
